server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training_auth

    username: postgres

    password: 123321

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

keycloak:
  auth-server-url: http://localhost:8081
  realm: master
  client-id: admin-cli
